### ISSUE TITLE
Fails to compile: "cannot use int(fd) (type int) as type syscall.Handle in function argument"

### ISSUE THREAD

**Issue by metaleap** [rcrowley/goagain#11]
Doing a **go get github.com/rcrowley/goagain** gives me:

```
C:\gd\src\github.com\ezbiz>go get github.com/rcrowley/goagain
# github.com/rcrowley/goagain
c:\gd\src\github.com\rcrowley\goagain\goagain.go:25: undefined: syscall.SIGUSR2
c:\gd\src\github.com\rcrowley\goagain\goagain.go:45: undefined: syscall.SIGUSR2
c:\gd\src\github.com\rcrowley\goagain\goagain.go:71: cannot use int(fd) (type int) as type syscall.Handle in function argument
c:\gd\src\github.com\rcrowley\goagain\goagain.go:92: undefined: syscall.Kill
```

This is **go version go1.0.3** 64-bit under Windows 7 64-bit. It's strange because _syscall.Kill_ and _syscall.SIGUSR2_ are _certainly_ "defined" under Go 1.0.3 as per the official pkg-docs..

Any idea what the issue could be here?

**Comment by rcrowley** [comment]
The `kill`(2) system call and `SIGUSR2` are very UNIX concepts.  I don't know anything about Windows but I'd wager this just isn't going to work.

**Comment by brendensoares** [comment]
@rcrowley are there no equivalent methods/approaches on Windows?

EDIT:
All of these seem relevant to the issue:
- http://www.perlmonks.org/?node_id=1022364
- http://msdn.microsoft.com/en-us/library/xdkz3x12.aspx
- http://stackoverflow.com/questions/813086/can-i-send-a-ctrl-c-sigint-to-an-application-on-windows
- http://stackoverflow.com/questions/140111/sending-an-arbitrary-signal-in-windows

It seems that we need to use Windows events instead of signals in order to be able to handle the parent/child messaging.

This is an active issue for revel/revel#747
